interface UnitWord {
  slovak: string;
  german: string;
  wordType: "NOUN" | "ADJECTIVE" | "VERB" | "OTHER";
  gender?: "MASCULINE" | "FEMININE" | "NEUTER";
  plural?: string | null;
}

export const unitWords: UnitWord[] = [
  {
    slovak: "večer",
    german: "Abend",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-e",
  },
  {
    slovak: "dobrý",
    german: "gut",
    wordType: "ADJECTIVE",
  },
  {
    slovak: "Ahoj!",
    german: "Hallo!",
    wordType: "OTHER",
  },
  {
    slovak: "ja",
    german: "ich",
    wordType: "OTHER",
  },
  {
    slovak: "ty",
    german: "du",
    wordType: "OTHER",
  },
  {
    slovak: "áno",
    german: "ja",
    wordType: "OTHER",
  },
  {
    slovak: "ráno",
    german: "Morgen",
    wordType: "NOUN",
    gender: "MASCULINE",
  },
  {
    slovak: "meno",
    german: "Name",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-n",
  },
  {
    slovak: "byť",
    german: "sein",
    wordType: "VERB",
  },
  {
    slovak: "deň",
    german: "Tag",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-e",
  },
  {
    slovak: "my",
    german: "wir",
    wordType: "OTHER",
  },
  {
    slovak: "kto",
    german: "wer",
    wordType: "OTHER",
  },
  {
    slovak: "v",
    german: "in",
    wordType: "OTHER",
  },
  {
    slovak: "nedaleko",
    german: "in der Nähe",
    wordType: "OTHER",
  },
  {
    slovak: "hra",
    german: "Spiel",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "kde",
    german: "wo",
    wordType: "OTHER",
  },
  {
    slovak: "nula",
    german: "null",
    wordType: "OTHER",
  },
  {
    slovak: "jeden",
    german: "eins",
    wordType: "OTHER",
  },
  {
    slovak: "dva",
    german: "zwei",
    wordType: "OTHER",
  },
  {
    slovak: "tri",
    german: "drei",
    wordType: "OTHER",
  },
  {
    slovak: "štyri",
    german: "vier",
    wordType: "OTHER",
  },
  {
    slovak: "päť",
    german: "fünf",
    wordType: "OTHER",
  },
  {
    slovak: "šesť",
    german: "sechs",
    wordType: "OTHER",
  },
  {
    slovak: "sedem",
    german: "sieben",
    wordType: "OTHER",
  },
  {
    slovak: "osem",
    german: "acht",
    wordType: "OTHER",
  },
  {
    slovak: "deväť",
    german: "neun",
    wordType: "OTHER",
  },
  {
    slovak: "desať",
    german: "zehn",
    wordType: "OTHER",
  },
  {
    slovak: "jedenásť",
    german: "elf",
    wordType: "OTHER",
  },
  {
    slovak: "dvanásť",
    german: "zwölf",
    wordType: "OTHER",
  },
  {
    slovak: "trinásť",
    german: "dreizehn",
    wordType: "OTHER",
  },
  {
    slovak: "štrnásť",
    german: "vierzehn",
    wordType: "OTHER",
  },
  {
    slovak: "pätnásť",
    german: "fünfzehn",
    wordType: "OTHER",
  },
  {
    slovak: "šestnásť",
    german: "sechzehn",
    wordType: "OTHER",
  },
  {
    slovak: "sedemnásť",
    german: "siebzehn",
    wordType: "OTHER",
  },
  {
    slovak: "osemnásť",
    german: "achtzehn",
    wordType: "OTHER",
  },
  {
    slovak: "devätnásť",
    german: "neunzehn",
    wordType: "OTHER",
  },
  {
    slovak: "dvadsať",
    german: "zwanzig",
    wordType: "OTHER",
  },
  {
    slovak: "starý",
    german: "alt",
    wordType: "ADJECTIVE",
  },
  {
    slovak: "mesiac",
    german: "Monat",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-e",
  },
  {
    slovak: "on",
    german: "er",
    wordType: "OTHER",
  },
  {
    slovak: "ona",
    german: "sie",
    wordType: "OTHER",
  },
  {
    slovak: "oni, ony",
    german: "sie",
    wordType: "OTHER",
  },
  {
    slovak: "ale",
    german: "aber",
    wordType: "OTHER",
  },
  {
    slovak: "vek",
    german: "Alter",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-",
  },
  {
    slovak: "tiež, aj",
    german: "auch",
    wordType: "OTHER",
  },
  {
    slovak: "z",
    german: "aus",
    wordType: "OTHER",
  },
  {
    slovak: "(hudobná) skupina",
    german: "Band",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-s",
  },
  {
    slovak: "chatovať",
    german: "chatten",
    wordType: "VERB",
  },
  {
    slovak: "počítačová hra",
    german: "Computerspiel",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "e-mail",
    german: "E-Mail",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-s",
  },
  {
    slovak: "angličtina",
    german: "Englisch",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: null,
  },
  {
    slovak: "fanúšik",
    german: "Fan",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-s",
  },
  {
    slovak: "francúzština",
    german: "Französisch",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: null,
  },
  {
    slovak: "kamarát, priateľ",
    german: "Freund",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-e",
  },
  {
    slovak: "priateľka",
    german: "Freundin",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-nen",
  },
  {
    slovak: "najlepšia kamarátka",
    german: "beste Freundin",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: null,
  },
  {
    slovak: "ísť, chodiť",
    german: "gehen",
    wordType: "VERB",
  },
  {
    slovak: "rád",
    german: "gern",
    wordType: "OTHER",
  },
  {
    slovak: "gitara",
    german: "Gitarre",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-n",
  },
  {
    slovak: "mobilný telefón",
    german: "Handy",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-s",
  },
  {
    slovak: "hobby, záľuba",
    german: "Hobby",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-s",
  },
  {
    slovak: "počúvať",
    german: "hören",
    wordType: "VERB",
  },
  {
    slovak: "surfovať na internete",
    german: "im Internet surfen",
    wordType: "VERB",
  },
  {
    slovak: "vždy, stále",
    german: "immer",
    wordType: "OTHER",
  },
  {
    slovak: "rok",
    german: "Jahr",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "žiadny/žiadna/žiadne",
    german: "kein/keine/kein",
    wordType: "OTHER",
  },
  {
    slovak: "klavír",
    german: "Klavier",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "pochádzať (z)",
    german: "kommen (aus)",
    wordType: "VERB",
  },
  {
    slovak: "učiť sa",
    german: "lernen",
    wordType: "VERB",
  },
  {
    slovak: "ležať",
    german: "liegen",
    wordType: "VERB",
  },
  {
    slovak: "koncert",
    german: "Konzert",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "priezvisko",
    german: "Nachname",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-n",
  },
  {
    slovak: "nedaleko (koho, čoho)",
    german: "nicht weit von",
    wordType: "OTHER",
  },
  {
    slovak: "cestovať",
    german: "reisen",
    wordType: "VERB",
  },
  {
    slovak: "písať",
    german: "schreiben",
    wordType: "VERB",
  },
  {
    slovak: "škola",
    german: "Schule",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-n",
  },
  {
    slovak: "hrať",
    german: "spielen",
    wordType: "VERB",
  },
  {
    slovak: "tancovať",
    german: "tanzen",
    wordType: "VERB",
  },
  {
    slovak: "bydlisko",
    german: "Wohnort",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-e",
  },
  {
    slovak: "nesprávny, chybný",
    german: "falsch",
    wordType: "ADJECTIVE",
  },
  {
    slovak: "flauta",
    german: "Flöte",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-n",
  },
  {
    slovak: "mať (vlastniť)",
    german: "haben",
    wordType: "VERB",
  },
  {
    slovak: "(hudobný) nástroj",
    german: "Instrument",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-e",
  },
  {
    slovak: "teraz",
    german: "jetzt",
    wordType: "OTHER",
  },
  {
    slovak: "robiť",
    german: "machen",
    wordType: "VERB",
  },
  {
    slovak: "šport",
    german: "Sport",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: null,
  },
  {
    slovak: "športovať",
    german: "Sport treiben",
    wordType: "VERB",
  },
  {
    slovak: "squash",
    german: "Squash",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: null,
  },
  {
    slovak: "jóga",
    german: "Yoga",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: null,
  },
  {
    slovak: "skoro",
    german: "bald",
    wordType: "OTHER",
  },
  {
    slovak: "do",
    german: "bis",
    wordType: "OTHER",
  },
  {
    slovak: "pekný",
    german: "schön",
    wordType: "ADJECTIVE",
  },
  {
    slovak: "znovustretnutie",
    german: "Wiedersehen",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "-",
  },
  {
    slovak: "Ahoj! (pri lúčení)",
    german: "Tschüs!",
    wordType: "OTHER",
  },
  {
    slovak: "Dovidenia!",
    german: "Auf Wiedersehen!",
    wordType: "OTHER",
  },
  {
    slovak: "pani",
    german: "Frau",
    wordType: "NOUN",
    gender: "FEMININE",
    plural: "-en",
  },
  {
    slovak: "pán",
    german: "Herr",
    wordType: "NOUN",
    gender: "MASCULINE",
    plural: "-en",
  },
  {
    slovak: "múzeum",
    german: "Museum",
    wordType: "NOUN",
    gender: "NEUTER",
    plural: "Museen",
  },
  {
    slovak: "Dobrý večer!",
    german: "Guten Abend!",
    wordType: "OTHER",
  },
  {
    slovak: "Dobré ráno!",
    german: "Guten Morgen!",
    wordType: "OTHER",
  },
  {
    slovak: "Dobrý deň!",
    german: "Guten Tag!",
    wordType: "OTHER",
  },
];
